### ISSUE TITLE
URL locator does not work in polytomy view

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#100]
For instance, if I go to http://www.onezoom.org/life.html/@=304358?vis=polytomy and search for Human, I get taken to a leaf and the URL gets changed to http://www.onezoom.org/life.html/@Homo_sapiens=770315?vis=polytomy#x344,y982,w2.1606 but If I reread, or copy and paste that URL into the browser, it goes back to the root of the tree.

This needs to be fixed before making the polytomy view very public

**Comment by jrosindell** [comment]
@lentinj Please can you look into this issue.  It probably does need to be fixed as part of OTOP because it's part of basic polytomy view functionality.

Having just said this @hyanwong I just tested the links you posted above and it does work for the version on the live OneZoom site - can you try and repeat the bug - what browser were you using?

**Comment by jrosindell** [comment]
Update - I've tested on Chrome and Safari and not managed to repeat the bug. I also tried moving the view and reloading in a different location and it worked...

**Comment by hyanwong** [comment]
Very weird. This works now - was using latest safari (and  think chrome), and tested repeatedly nd it didn't work. Gremlins in my system...
