### ISSUE TITLE
Zooming into high-branched areas results in a moosh of signposts

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#111]
![image](https://user-images.githubusercontent.com/586911/41845394-3da6c40c-786b-11e8-9d79-42d2478aa4af.png)

Just disable signpost when there's lots of branching? We could do some fancy logic to avoid overlapping signposts, but even if we had a few signposts at this point, it won't be obvious what they're pointing at.

**Comment by jrosindell** [comment]
I don't think this is the correct solution.  The thresholding disables drawing for small signposts.  I agree with you that fancy logic to avoid overlapping signposts is unnecessary here and possibly bad as a bit of overlap is quite nice.  However, the logic that chooses signpost size overall is a but broken in my view.  Signposts should at least be proportional to the horizon of the descendent node.  Maybe you could get away with something of form signpost size = a * horizon size ^ b or even - I'm not sure how they are calculated now but I think it's based somehow on the horizon of the parent node not the horizon of the node to which the signpost itself refers.

**Comment by jrosindell** [comment]
<img width="523" alt="untitled2" src="https://user-images.githubusercontent.com/3009279/41851766-88b6f476-78bb-11e8-9f23-6de214dbc005.png">
In this example the three overlapping signposts do not look a suitable size.

**Comment by lentinj** [comment]
If you draw on the node bounding boxes, it's obvious why you can't use them---they include the parent bounding box (or probably more precisely, the branch to the parent). Thus why they're too big in the screenshot.

Obvious solution: Look at the bounding boxes of the nodes' children. This produces much better results, until you get to high-branching areas where the node isn't necessarily developed and xvar/rvar might not be updated / set in the first place.

Filtering children that don't have xvar/rvar updated isn't immediately obvious, ``node.graphref`` filters too much and basically turns signposts off.

It may be quicker/faster to base it on the branch length anyway.

This seems to be related to #108 though. I can actually make it into some of the high-branched areas now.

**Comment by jrosindell** [comment]
I think you're right about all this.  

One possible thought about the solution to this is to tweak the logic that decides where to stop when rippling down the tree and drawing signposts.  If children are not developed properly or don't have xvar/rvar for all children then you simply don't allow the signpost logic to ripple down and have the parent be the signpost instead.  At present signpost logic rippling is based entirely on signpost size - from memory this means if current signpost is too big the you ripple down.  Which is fine for bifurcating trees, but in polytomy trees you could have current signpost too big whilst child signposts are too small / undefined. Hence the logic should be updated to reflect this.

Maybe in such cases allow the parent to show the signpost but reduce the size of it so that it doesn't totally dominate the area and instead appears underneath the (otherwise boring) fanning part of the massive polytomy.  So, in my 25th June example, the three signposts at the bottom would none of them be drawn and instead a single larger (but not that large!) signpost would be drawn for the parent node of those three.

I hope I've explained this clearly enough - it's a complex business!

**Comment by lentinj** [comment]
Okay, apparently what I should be checking was if the parent ``node.rvar > tree_state.threshold``. Beyond that we give up and let the child x/y/r/var properties lapse:-

https://github.com/OneZoom/OZtree/blob/82afebc1448ef7d1193f196ef5c54e946f02270b/OZprivate/rawJS/OZTreeModule/src/projection/re_calc.js#L81

Looking at gvar/dvar gave too many false positives, but this seems to work.

I suspect at this point we should set x/y/rvar to undefined rather than leaving old values around, it doesn't seem to be producing ill-effect.

Another problem is that e.g. zooming into Dilleniales and back out to Gunneridae and back in again, we get stuck. This does seem somehow related to these signpost changes, but I've not fathomed how.

**Comment by lentinj** [comment]
Right, I think the above sorts this. Even in pretty extreme levels of branching, it manages to do the right thing(tm).

> Another problem is that e.g. zooming into Dilleniales and back out to Gunneridae and back in again, we get stuck. This does seem somehow related to these signpost changes, but I've not fathomed how.

This seems to be a problem with my data locally. I can't replicate against the beta server.

**Comment by hyanwong** [comment]
> This seems to be a problem with my data locally. I can't replicate against the beta server.

I suspect you are using the old ordered_nodes and ordered_leaves tables, which had some mistakes. I will wetransfer you some new ones (which correspond to files in commit 1cf5f6cf74ad609199b0d1a8545fb3450b89dd9a, so you'll need to sync up to get them to work)

**Comment by hyanwong** [comment]
@lentinj @jrosindell : I have just emailed both of you a link to the new sql data files for the ordered_leaves and ordered_nodes tables. Let me know if you have problems loading/using them.
