### ISSUE TITLE
Touch pan/click disambiguation

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#155]
I found that when you touch on a signpost or clickable element, then move your finger the highlighting of the touchable element continues, it used to be in an earlier version that as soon as you're panning instead (and thus the highlighted action will not take place on end of touch) that the highlighting will stop.  Also, I found that touching / tapping signposts to zoom in doesn't work often on touch screens

**Comment by lentinj** [comment]
Probably related, touching leaf nodes (to bring up wikipedia) only works if you give your finger a wiggle too. Sounds like a refresh loop bug.

**Comment by lentinj** [comment]
Yes, the latter part of the above is the same as my comment, just signposts instead of leaf nodes.

In that case, we've registered a click but the tree hasn't been redrawn, since nothing moved. Because the tree hasn't been redrawn, we don't know that the finger is over a thing that needs clicking.

The hack to fix this is to jiggle the tree in ``touch_start`` with ``this.controller.pan(1, 0);``. Very ugly, but works. I think we leave this nearer the end and see if there's time to find a better fix.

NB: This is related to ``trigger_refresh_loop``, but not directly. Directly triggering the refresh loop will cause long non-moving touches to click, but only after a delay (a condition that the tree isn't redrawn unless it's moved or some time has passed rings a bell, and I think that's the real villain here).

**Comment by jrosindell** [comment]
Agreed, it's good that it's fixed but hopefully there will be a better fix to be done later
