### ISSUE TITLE
Issue on OneZoom/life for preloading images on flight

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#159]
For a while now (and still after just syncing my code with v. 3.3 branch) it's been the case on my local instance that when clicking on the links for a flight through the tree it starts the flight before preloading the images and text needed to make the flight good.  Recently it got worse as the unloaded parts of the tree now show as grey circles when previously they were green circles and ideally they should be green leaves.  

It's marked as essential because it worked before the OTOP developments and if we make this live as it stands it will severely impact the quality of the experience of using OneZoom for ordinary users.

**Comment by jrosindell** [comment]
This is related to #11  but still it's worse than it used to be because now the images and API retrieved information doesn't load whereas before it was just about the look and feel of the fake leaves

**Comment by lentinj** [comment]
I think what you're talking about here is initial flights in particular, e.g. ``/life/@Macroscelides_proboscideus=180378?init=zoom``. The problem here was that ``perform_flight_animation`` wasn't fetching initial detail before flying. The above swaps it out for the more complete perform_flight_transition, which does. A side effect of this is zoom / pzoom are now non-linear, but for zoom I think this is an improvement, for pzoom it's too subtle to get excited about either way.

Images OTOH are loaded as they come into view and AFAIK always have done. I don't think it's reasonable to expect users to wait for them all to load for a long flight anyway.

**Comment by jrosindell** [comment]
OK this looks good to me, thanks @lentinj
