### ISSUE TITLE
Back button behaviour in /life and /otop

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#166]
The web browser back button leads to bugs.  For example just going to 

/life.html/@Mammalia?init=zoom

and pressing the back button leads to bug where the tree is not drawn properly.  This is possible related to #165 

<img width="877" alt="OZ bug march19" src="https://user-images.githubusercontent.com/3009279/54886809-17980880-4e84-11e9-8208-dbdf5d7507a1.png">

**Comment by lentinj** [comment]
In safari 12.0.3

**Comment by lentinj** [comment]
``record_url()``, as well as adding the current position to the browser history, also adds a state object into the browser's history. ``popupstate`` attempts to pick this up and use it to restore the page state.

However, since that state object is intended for making a URL, the x/y/w values are rounded strings, not integers. This causes the restore to fly off in arbitrary directions.

**Comment by lentinj** [comment]
The above removes the somewhat-broken state object from the browser's history, and instead re-parses the query. It may be worth fixing the state object so it doesn't convert to string until forming the hash, but that's now a non-issue.
