### ISSUE TITLE
Links do not escape the iframe within the tree view on OTOP

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#169]
The title says it all - the links need to open in a new tab

**Comment by hyanwong** [comment]
There's a setting for that.

**Comment by hyanwong** [comment]
```
#popups->vars          Passed to pic_info.load, about.load, how.load, data_sources.load, and the 
#                       internal linkouts urls. You will usually want to define 'embed':1 or 'embed':3 (see embed.html). 
#                       It's also sensible to set 'form_reservation_code' to a UID so that re-opening sponsor tabs remembers who you are
```

**Comment by hyanwong** [comment]
From what I documented in embed.html, I think you want to set `embed=2` on this line: https://github.com/OneZoom/OZtree/blob/91bde1b2f00da29ae4b1d77f3ee1ed2928b7e4c8/views/treeviewer/otop.html#L37 as documented at https://github.com/OneZoom/OZtree/blob/91bde1b2f00da29ae4b1d77f3ee1ed2928b7e4c8/views/embed.html#L34

**Comment by hyanwong** [comment]
Also all links in tab pages need to be constructed with the `A()` helper, so that the function can be modified to add `_target="_blank"`. This wasn’t done for  views/tree/leaf_linkouts.html and  views/tree/node_linkouts.html. I have changed it with https://github.com/OneZoom/OZtree/commit/93654df2e26c27d3ee7718b5880e9126f2332402

**Comment by hyanwong** [comment]
@jrosindell please check this is now solved

**Comment by jrosindell** [comment]
It opens in a new tab when I test locally.  So yes, I think this is solved.  If it doesn't escape the app then this is related to the app settings.
