### ISSUE TITLE
tour transition data format

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#197]
ott_end_id should be got rid of
ott will give the end destination regardless of how you got there - the options should simply be to either get there by jump or zoom. This also solves an issue which we thought was fixed by https://github.com/OneZoom/OZtree/commit/3ad33f26bc1e6c8499fce4c3bc6bdb6446809113 but appears not to be.
[optional - we should probably have an option to specify whether or not the tour box is shown during flight, if flying - this could be an extra transition option, e.g. "transition = `jump`, `fly`, or `showfly`]

The rationale is that tour stops can then not only be read individually but also chained in any order.  We will be need to be careful when writing tours that only appropriate information is put into the tour_stop_shared section e.g. 'next bioluminescent creature' not stop default options that would mess up if taken out of context.

We can emulate the current behaviour by creating an intermediate stop

**Comment by hyanwong** [comment]
We have removed `ott_end_id ` and implemented `transition_in="fly"|"leap"|"fly_straight"`. With the pausing ability [fixed by kai](https://github.com/OneZoom/OZtree/issues/203) and the extra `exec` functionality added in a6a4ebd192564a3db40719c478e807ace082294e, I think the spec for the tour data format is now finished. The example of the format is also now embedded in the Tours.js file (see 95988582f2ad7118c99c5d797519011006464f97), so it should be obvious how to document the tour settings format if it changes.
