### ISSUE TITLE
Previous button on tour now doesn't work properly

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#207]
I don't know if we still have any developer time left with you @kz12, but after adding the chained promises (thanks!) and adding a wait time before transition in 3b6e4aec1bb9fd9352216cac130f14999735b8c1, it appears that the previous button now takes you back to the start of the current tourstop, rather than all the way back to the previous one. Sot it is very difficult to keep clicking "previous" to go back through the stops. If you still have dev time left, you think you can figure out how to correct this, @kz12 

Ping @jrosindell for info etc.

**Comment by hyanwong** [comment]
One problem might be that we are no longer skipping "hidden" stops. We might need to code this back in, or try not to have any hidden stops.

**Comment by hyanwong** [comment]
I've added `exec.on_stop` and `exec.on_transition` so these might need to be incorporated into our thinking about how "previous" and "skip" work.

**Comment by kz12** [comment]
@hyanwong- Does it happens to all tour stops, or just a specific one?

**Comment by hyanwong** [comment]
In 026d2724fa43698c8a3b2d9131340eaa75c3a338 I removed the "blank" stop that I previously had coded in tutorial_MD.js (see comment). But I think it's still a problem when trying to repeatedly click on back to go through the stops. We should also check that we can easily skip forwards through the stops by clicking on "skip" every (say) half second, and that when we stop clicking "skip", other events and flying transitions are stopped.

**Comment by kz12** [comment]
> In [026d272](https://github.com/OneZoom/OZtree/commit/026d2724fa43698c8a3b2d9131340eaa75c3a338) I removed the "blank" stop that I previously had coded in tutorial_MD.js (see comment). But I think it's still a problem when trying to repeatedly click on back to go through the stops. We should also check that we can easily skip forwards through the stops by clicking on "skip" every (say) half second, and that when we stop clicking "skip", other events and flying transitions are stopped.

There is a bug in tour stop. When a tour stop exit, it would call pause. This should stop fly animation and invoking of `complete_tourstop`. But now it isn't.

**Comment by hyanwong** [comment]
Ah, OK. Would you we willing to help fix this, @kz12 ? I removed the `TourStop.hide()` call on exit, as we sometimes want the previous stop to be shown during the transition into the next stop. But I didn't think I had changed any other logic.

By the way, we are now developing on the "3.4" branch, although I've been cherry-picking the commits from there onto `education-functions` for you. You might want to switch to 3.4, although it may force some updating of your database tables, which might take a little time. The I can delete the `education-functions` branch.

**Comment by kz12** [comment]
> By the way, we are now developing on the "3.4" branch, although I've been cherry-picking the commits from there onto `education-functions` for you. You might want to switch to 3.4, although it may force some updating of your database tables, which might take a little time. The I can delete the `education-functions` branch.

Would the database file be big? The transferring speed is quite slow here

**Comment by hyanwong** [comment]
I don't think you need to transfer anything new. It's only that when you switch to 3.4, web2py will create some new (empty) columns in some of your tables. If any of the tables are large, that could take a few minutes. But I think the main one is the reservations table, and I'm assuming yours is empty, so that shouldn't be much of a problem

**Comment by kz12** [comment]
I've switched to 3.4 and it works well now. Could you log onto Skype? It would be more convenient to speak there.

**Comment by kz12** [comment]
I think sometimes go previous fails due to the following reason:

When it is at tour stop N+1, and user click on previous to goto N. The `complete_tourstop` of N+1 would still be invoked. Meanwhile, the tour stop N would call `play`. However, @jrosindell and I have decided if `play` is invoked after pressing prev button, it should `leap` to the target position. Hence, the `complete_tourstop` of tour stop N would be called after `leap`. Because `leap` is actually a sync function and `fly` is `setTimeout` or `requestAnimationFrame` based async function. Therefore, the `complete_tourstop` function of N+1 would be called after `complete_tourstop` of N.

Therefore, when you press previous on N+1, you would see container of N first and then N+1. Or if it happens very quickly, you would see only N+1 and the view would jump to the end of N.

**Comment by kz12** [comment]
I think the solution is in `complete_tourstop`, if the state of the tour stop is `TOURSTOP_EXIT`, then this function should be skipped.

**Comment by hyanwong** [comment]
Hi @kz12  - I'm about to go out, so don't have time to Skype, sorry! Tomorrow morning?

**Comment by hyanwong** [comment]
Also, when you click "skip", it should do a "leap_to" immediately to the next location. At the moment, if you press skip repeatedly quickly, you can end up at a location that has nothing to do with the currently showing box.

**Comment by hyanwong** [comment]
Another issue is that sometime pressing next fast leads to a "goto_next" event firing *after* the tour has exited, which leads to the text of the tour box (but strangely, not the yellow div in which it normally sits) being revealed even after the end of the tour. A picture is attached:
![Screenshot 2019-09-21 at 16 05 28](https://user-images.githubusercontent.com/4699014/65375115-bd88cc00-dc89-11e9-8d89-a37074194b00.png)

**Comment by kz12** [comment]
@hyanwong - We can have the meeting tomorrow morning(London Time), how about 8am?

I've updated the code [5f34a53ebfb3] and [b5c62607525832]. Now the skip button and previous button should be much more smoother.

I don't know the reason for the tour box being revealed. Although I do see it once, but I can't repeat it.

The issue of skip and previous are not working or not working correctly is because the async functions are still running after the tour stop exits. 

There are still some outstanding issues left:
1. Detailed information tour box is shown out of the left boundary. 
2. when the tour box of the first tour stop continues to show on the second tour stop, user might feel that the next button is not working, because the tour box is still showing after press next.

**Comment by hyanwong** [comment]
I’m only just going to sleep now, so 9am UK time would be better if possible. Is James available too?

**Comment by kz12** [comment]
OK. Let's meet at 9am
