### ISSUE TITLE
Popular places for homepage

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#214]
Have generated by backend

**Comment by lentinj** [comment]
Notes from call 2019-11-08:

* Popular places can be tours too, so would also need name/ott images/ (but that'd be part of the notional tours table)
* Don't try and do a random selection, just show them all, and will ~manually rotate the 20 items in the DB

**Comment by jrosindell** [comment]
A few additional points to add
- [ ] the carousel should have 5 things showing with sizes decreasing as designed in the mockup.
- [ ]  carousel should connect to tree_startpoints table in database and use 'category' to decide if the data should be used for the popular places or the front page animated tree tour stops
- [ ] carousel items should occupy less space on a narrower screen so that 5 items are always shown.  carousel items should not be cut off harshly with vertical lines at the edge of the space allowed.

**Comment by lentinj** [comment]
To get the popular places slider to slide in all cases, I've filled it with elephants(they are the best) - https://github.com/OneZoom/OZtree/commit/bf30ba641f6deb9358e661bcacc4578d740e276a .

My ``tree_startpoints`` table is empty currently, so it's probably more faff than it's worth for me to set up the controller properly. But replacing the hard-coded list should be plenty easy.

**Comment by hyanwong** [comment]
> My `tree_startpoints` table is empty currently, so it's probably more faff than it's worth for me to set up the controller properly. But replacing the hard-coded list should be plenty easy.

Yep, I'm happy to do that.
