### ISSUE TITLE
Homepage endangered example species

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#225]
We decided this is a possible solution to the odd biodiversity / convservation section. Add some example species to make the section higher, and thus less "ribbony".

**Comment by lentinj** [comment]
@jrosindell I've slopped some swifts in with the above. Do you think it's an improvement? If so, I'll plumb in a bit of controller to finish.

It looks a bit plain, I did try putting a red border around them but didn't really match the look of any others. But if you think it's a good idea we can always poke Matt.

**Comment by hyanwong** [comment]
James explained this to me, and I was a little unconvinced, but actually, now that you've done it, I think this looks great! I don't think they need a red border. We can pick very obviously endangered species to put there. If it's easy to stick in a controller (rather than to code them in statically) then please do - the controller can just return some static images, and I can re-code it as necessary.

**Comment by lentinj** [comment]
The above moves the hard-coded list back to the controller, in an identical fashion to the popular places. So it should be nice and easy to convert both to using the tree_startpoints table (I'm guessing this is what will happen?)

**Comment by hyanwong** [comment]
Thanks @lentinj - I can take it from here. I hadn't thought about using the tree_startpoints table, but that does make sense now that you mention it.
