### ISSUE TITLE
OneZoom Embed editor / key generator

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#283]
We used to support this a long time ago...

`                 <h4>Link to or embed OneZoom</h4>
                 <p>
                 We welcome you to use our new <a href="embed.htm">link and embed</a> tool to link to OneZoom or embed it as html in your own website or blog.  The tool is really easy to use, choose the options you want and it will generate a short piece of code or a hyperlink for you to copy and paste. You can choose your own styles and colours as well as create custom animations that fly through the tree to your speces or taxa of interest.
                 </p>
`

All this is old now, but it would make sense to provide some easy to use instructions on how to embed the up to date tree.

**Comment by jrosindell** [comment]
We'll likely be rethinking the whole embedding method so that it doesn't use an iframe and instead uses some kind of embedded JS package that can easily be added to a page and that calls the OneZoom API (with an API key) to grab the most up to date information.  We will obviously need an instruction page to explain roughly how to do this with an example bit of code or a simple code generation feature.  This will probably require some discussion to flesh out properly.

**Comment by lentinj** [comment]
We would like a similar page, that generates a bunch of embed code via. e-mail. In the process we get an e-mail address to associate a key to (which will be embedded into the generated code).

There'd need to be a database associating emails, domains & generated keys, along with an "invalidated" timestamp if they need to be stopped for whatever reason.

Include the chosen settings as part of the embed code, rather than storing them against the key, so it's easy to alter then after the fact rather than having to remember what you selected and regenerate your embed.

Stick with iframes, to at least keep the onezoom.org and third party site origins separate. If this isn't enough, then it would be up to the third party to manage a minlife-style installation, which is out of scope for today.

[Signing embed keys as per Google Maps](https://developers.google.com/maps/documentation/maps-static/digital-signature) is excessive, at least for now.

**Comment by lentinj** [comment]
Remaining work:

- [ ] Tree view selection
- [ ] Image type selection
- [ ] Language selection
- [ ] Generate / store keys for e-mail addresses

**Comment by lentinj** [comment]
The above generates keys for given e-mail addresses, and adds them to the e-mailed URLs. We don't do any checking of the values used, nor enforce a value to be used. Do we want to at this stage?

**Comment by jrosindell** [comment]
I think we're OK with not checking them at this stage - I see they are being stored so that's enough
