### ISSUE TITLE
Tabs in treeviewer popup window do not show visual change

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#288]
Weirdly, when clicking a new tab in the treeviewer popup window (say "Genetics" rather than "Wikipedia"), the little blue line which denotes which tab you are viewing does not change, and the tab text colour does not go darker. Here is an example where the "Genetics" tab is selected (although it doesn't appear to be)

![Screenshot 2020-04-05 at 23 49 24](https://user-images.githubusercontent.com/4699014/78511927-63b8a100-7798-11ea-9faa-7d80900de91d.png)

**Comment by hyanwong** [comment]
This seems like a UIkit bug (I get the same behaviour in the demos at https://getuikit.com/docs/tab ). I have raised in on their discussion forum.

**Comment by lentinj** [comment]
I'd assume the comment in the event handler below is relevant and that it's an attempt to stop show/hidden events of the main modal being fired also:

https://github.com/OneZoom/OZtree/blob/44f3d5e5e6059bcf39d2c289983684b3e3ff81f9/views/treeviewer/layout.html#L794-L797

It has to be related to the modal dialog, since there isn't really anywhere else these events would propagate up to, since ``#external-modal`` is at the top of the HTML tree. Like the commenter says, I doubt they serve much purpose. 

Another option would be to change the selector from ``#external-modal .popup-container li`` to ``#external-modal .external-content``, that way the uk-switcher / uk-tabs get to do their thing first before any custom logic happens. Then the event propagation could be stopped with no ill effect. This would be more reasonable from a browser's point of view, since it's only 1 event listener for all tabs, versus 1 event listener for each.

**Comment by hyanwong** [comment]
Thanks @lentinj  - I realise this is a bit off your patch but thought you might have a sensible take. The comment *is* still pertinent  - when you remove the `on(hide)` handler, switching to another tab hides the current tab, and the event bubbles up, which hides the entire tabbed window. It seems that's not a problem with the `on(show)` handler, though. Nevertheless, I like your idea above, though. I'll try to implement and see how it goes. Thanks again.

**Comment by hyanwong** [comment]
@lentinj - can I just clarify your comment about "changing the selector from `#external-modal .popup-container li` to `#external-modal .external-content`". At the moment the code causing the issue is:

```
    $('#external-modal .popup-container li').on('show', function (event) {
        if ($(event.currentTarget).attr("data-src")) {
            load_tab($(event.currentTarget));
        }
        event.stopPropagation();
    });
```

If the selector changes to `#external-modal .external-content` then (a) how does this get fired when an individual tab is changed (does it just bubble up)? and (b) how can we tell which tab has been loaded? We current use `$(event.currentTarget).attr("data-src")` to get the specific tab information, but won't the `event.currentTarget` have been changed to the `.external-content` div, which doesn't have the correct info?

**Comment by lentinj** [comment]
>  (a) how does this get fired when an individual tab is changed (does it just bubble up)?

Should do. It could be disabled on a custom event but pretty sure ui-kit doesn't.

>  (b) how can we tell which tab has been loaded?

Whoops, I didn't notice it was ``currentTarget`` not ``target``. You're correct. You can do something like ``$(event.target).closest('li')`` or ``event.target.closest('li');`` (requires a polyfill for IE).
