### ISSUE TITLE
Wikipedia page embedding not working

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#310]
I suspect a problem with CSS on embedded image and display components.  See the below attached screenshots from Chimpanzee example on live website and on beta website.

<img width="1417" alt="OZ" src="https://user-images.githubusercontent.com/3009279/79641903-4e794480-8192-11ea-96a0-287f7ab9d818.png">
<img width="1381" alt="BetaOZ" src="https://user-images.githubusercontent.com/3009279/79641904-520ccb80-8192-11ea-8622-b60d0c40629a.png">

**Comment by hyanwong** [comment]
Any JS errors in the console?

**Comment by hyanwong** [comment]
OK, this seems to be because UIkit is setting `img {max-width: 100%}` in the css. If we turn that off, the images are sensible size again, and so the captions are OK. I'm not sure why this is not a problem on production though.

**Comment by hyanwong** [comment]
So production (sensibly) doesn't include the uikit css in the iframe. Not sure why dev does. Investigating...

**Comment by hyanwong** [comment]
OK, I see why. When embedding our own pages, like the sponsor leaf pages, etc, we normally *want* to have the UIkit styles. This allows us to put stuff like the background leafy pictures in, etc. However, the wikipedia page is an exception, because we really don't want to style it that much (although we do want to e.g. use `class="wikipage-source"` which is styled in content_pages.scss). I think the best thing is to treat this specific page as special, and not load the uikit css and js etc.

**Comment by hyanwong** [comment]
Fixed with #309
