### ISSUE TITLE
Sort out error handling for flight interruption

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#325]
With #324 we hacked around the issue reported at https://github.com/OneZoom/OZtree/issues/231#issuecomment-617719250. But the real solution is to work out why we are hitting this piece of error handling in the first place. 

I *think* the reason is that we are re-writing the URL when flying to a new place, which then involves calling `popupstate` which itself calls `setup_page_by_state`, which triggers the error. Presumably if the flight is interrupted we need to rewrite the URL using the location we end up in, without triggering an error. I might have this wrong, though.

**Comment by lentinj** [comment]
@hyanwong my guess was that ``setup_page_by_state`` is what starts the flight in the first place, so when you interrupt, and reject the chain of animation promises, it's just bubbling up the chain as it's supposed to. A better fix would be to catch the rejection in the same way, just further up in the animation code rather than falling this far. Then letting the rest of the page setup code continue.

**Comment by hyanwong** [comment]
Ah, that is probably right, thanks @lentinj

**Comment by jrosindell** [comment]
Yan has fixed this too with a recent push
