### ISSUE TITLE
URL with anim=jump still does a pzoom

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#491]
E.g. go to

https://www.onezoom.org/life/@Hippocampus_denise=3642226?anim=jump&pop=ol_3642226

I think this should jump straight there, right? Is this to do with the fix in https://github.com/OneZoom/OZtree/issues/254?

**Comment by jrosindell** [comment]
This URL parsed parameter relates to the default setting for the user when they are in the tree but apparently isn't not listened to for determining the introductory zoom / jump into the tree.

**Comment by lentinj** [comment]
This is intentional, isn't it? I believe you want ``init=jump`` as well as ``anim=jump`` to get the above.

parse_querystring() digs out both ``anim`` and ``init``:

https://github.com/OneZoom/OZtree/blob/3929f585b19ac259ca1637bc153872d083b4b94a/OZprivate/rawJS/OZTreeModule/src/navigation/utils.js#L135

...which then gets fed into ``init_move_to``():

https://github.com/OneZoom/OZtree/blob/3929f585b19ac259ca1637bc153872d083b4b94a/OZprivate/rawJS/OZTreeModule/src/navigation/setup_page.js#L98

What the valid use cases for varying both are, I can't remember. But I assume there are some somewhere.

**Comment by jrosindell** [comment]
Right, this makes sense.  I think the use case for having both separately is that pzoom doesn't make sense unless it's part of initialisation so we often want pzoom for init and zoom for anim
