### ISSUE TITLE
Weirdness with `raise` line in sponsor_pay() controller

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#503]
In order to get the "normal" behaviour when we punch out to PayPal, I had to reintroduce a `raise` statement that I don't understand. See #502. If this `raise` statement is removed, we always get a pages saying "Sorry, we couldn’t find your leaf sponsorship information."

I'm worried that I don't understand what's going on here. In addition, I'm no longer sure why we punch out to `sponsor_pay.html` in the form we set up on `sponsor_leaf.html`, rather than just open the same page again: that would seem much easier and also allow validation etc. This might be something to do with the paypal popup stuff though, so I'm reluctant to change much. I'm allocating this to @lentinj as I would like to know what the proper thing to do is, and I think he has the best grasp of the intricacies.

**Comment by lentinj** [comment]
> If this raise statement is removed, we always get a pages saying "Sorry, we couldn’t find your leaf sponsorship information."

Because ``redirect()`` works by raising an HTTP exception, which the except is eating unless you raise it again:

https://github.com/web2py/web2py/blob/c2ed5016e161430ecb020ddc96b16a6e5dde0e2e/gluon/http.py#L162-L187

FWIW ``sponsor_pay()`` is much tidier in 3.6.1:

https://github.com/OneZoom/OZtree/blob/3.6.1/controllers/default.py#L580-L608

...this needs ``sponsor_leaf_check`` to return a few more odds and ends to be dropped into an older codebase.

> I'm no longer sure why we punch out to sponsor_pay.html in the form we set up on sponsor_leaf.html

By 3.6.1 the split is entirely historical, sponsor_leaf could be an alias of sponsor_pay and I'm pretty sure everything would keep working.

> This might be something to do with the paypal popup stuff though, so I'm reluctant to change much.

Yes, this sounds possible. The basic idea of the pop-up mechanism was to spin round submitting a form within the iframe until it came back valid. If it came back valid then it would re-submit via. JS to sponsor_pay in a new window.

The commit removing it collates the various moving parts reasonably well:

https://github.com/OneZoom/OZtree/commit/6a93d6f12b0067f881823a199d6f063c361f5da6

**Comment by hyanwong** [comment]
> Because redirect() works by raising an HTTP exception, which the except is eating unless you raise it again:

Ah! That makes sense now. Thanks so much @lentinj !

I will hold off any changes until we merge and test 3.6.1

**Comment by jrosindell** [comment]
I think we may be able to close this issue now, but just checking with @hyanwong and @lentinj first

**Comment by lentinj** [comment]
Yeah, this is done and dusted I think.
