### ISSUE TITLE
Check current UI code is reasonably sound

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#58]
Since the current UI code in the repo will most likely be used for the museum display, we'd like to be sure that it's not poorly constructed in terms of its CSS / style / bugs etc.

**Comment by lentinj** [comment]
By the sounds of it, the emphasis here is on potential layout bugs, vs. potential exploits in code. Correct?

**Comment by hyanwong** [comment]
I think the code exploits are less of a problem here. The issue is mainly that the code logic is probably a little convoluted and could do with an outside eye. That would help e.g. if we needed in the future to change layouts or even the UI design.

Currently the code organisation it makes it harder work than it should be to track down e.g. layout bugs.

**Comment by hyanwong** [comment]
For example, the UI layer is injected over the top of the canvas via Ajax. I have done that so that the entire UI layer can be reloaded in a different language. But it means that there is one file, viewer_UI.load, which contains the actual injected html, while the javascript that manipulates that html is in the file into which the UI is injected (this is called treeLayout.html).

The system seems a bit convoluted - suggestions as to professional ways to tidy it up would be very useful. Or perhaps this is the correct way to do it?

**Comment by lentinj** [comment]
I'd have expected nowadays a relatively empty single page with say a canvas & div for the UI. Then the tree view and the UI are broken up as components on this page and told to have at it.

(most web frameworks if you use one have a concept of component, which are essentially a bundling of HTML and Javascript that operates on it. Your own code can be structured this way also too.)

Internationalisation can be handled within each component.

**Comment by hyanwong** [comment]
The internationalisation is done in web2py. So to change UI language, I need to reload a web2py page with a different flag (e.g. by setting a URL param 'lang=fr'). Unfortunately it's tedious to reload the canvas (which requires reloading the data for the tree), so I simply reload the div that contains the html components of the UI, via an ajax call. That seems reasonable, but it does make the code a little complex, especially as the JS which runs the UI can't be loaded via AJAX, as far as I understand. It forces a separation between the JS and the HTML identifiers etc which the JS needs to deal with.

**Comment by hyanwong** [comment]
I think this can be closed, since @lentinj will be inspecting the codebase along with other issues.
