### ISSUE TITLE
Search seems to give unexpected results

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#6]
Behaviour observed in Oxford botanic gardens on the touchscreen: often many non-hit search results are returned. I suspect this might be because of firing off the search too easily, so that if you type "collared", a search is requested for 'col' before the rest of the word is typed. Perhaps the search delay in the UI is too long, or is being ignored by the touchscreen.

**Comment by hyanwong** [comment]
Probably linked to https://github.com/OneZoom/OZtree/issues/7

**Comment by jrosindell** [comment]
This is related to the API being called and then the search box being updated.

Proposed solution.... check the API return for what the search results were meant to be for and only inject the results on the page if the text box content still matches what was returned from the call.

Also, I suggest that when one API call has been sent we wait for a reasonable amount of time (or until a return is seen) before allowing another to be sent, even if the text box is being updated.

Finally, we should probably increase the timer a little on the text box so that it's not so quick to fire the search API call whilst the user may still be typing.  E.g. at events with kids typing and spending a long time to find the next letter - that's when it broke most often

**Comment by jrosindell** [comment]
I do not know do much about how the api works - but the returns I'm seeing don't include an echo of the search string that was used to call the API in the first place.  Is there another way to match the calls up with their returns more reliably?

**Comment by jrosindell** [comment]
I think this is basically solved but I'm leaving the issue open until search is fully debugged.

One outstanding issue is that search box population with results still seems buggy.

**Comment by jrosindell** [comment]
This is now fixed with latest push.
