### ISSUE TITLE
Separate out viewer and site by changing URL structure (e.g. to onezoom.org/tree/@xxx)

### ISSUE THREAD

**Issue by hyanwong** [OneZoom/OZtree#60]
After a little thought, I wonder if it is sensible to make a cleaner separation of the tree viewing page(s) and the rest of the site. There is already a controller called "tree", so we could put life.html (the URL of the current viewer) as index.html in there, and change to urls of the form

`www.onezoom.org/tree/@Mammalia`

The advantage is that we could then collect all the viewer logic etc into a single directory, "tree". At the moment it is rather intertwined with the rest of the website, and it is difficult to find your way around the codebase.

As for other trees, e.g. LinnSoc, or Kew, we would instead use

`www.onezoom.org/tree/LinnSoc/@Mammalia`

and so on.

We should be able to maintain the old URLs, though, using redirections.

**Comment by hyanwong** [comment]
The nice thing about using "/tree" is that it leads to a URL which does what is says on the tin. I find it intuitive that the default tree is all life, and other extensions ("/tree/bacteria/", "/tree/plants/" etc) are subtrees.

**Comment by hyanwong** [comment]
Just encountered a potential problem with this, in that a url like

`www.onezoom.org/tree/@Mammalia` 

is interpreted as "controller=tree, function=@Mammalia", rather than "controller=tree, function=index(default), args=@Mammalia", so the URL would have to be the (rather ugly) `www.onezoom.org/tree//@Mammalia`. I don't think this is worth it for the time being...

**Comment by hyanwong** [comment]
This is coded up on the "controller-rearrangement" branch

**Comment by hyanwong** [comment]
p.s. any other suggestions for enforcing a clean separation between the pages involved in the site and the pages involved in the tree viewer would be useful. For example, we could have a separate controller "site", to contain all the site-specific (non-viewer) stuff instead, and reserve the default controller for the treeviz.

**Comment by jrosindell** [comment]
These are all useful thoughts.  I agree that the URL could do with a rethink for these reasons.  However, every time we change the URL structure it potentially breaks links to us from social media and other traffic sources unless we're careful.  I would suggest that we leave this for a longer term enhancement as part of a much broader rethink of the project as a whole so that the URL scheme only needs to be changed one more time in the foreseeable future.

For example, I would like to replace the parsed parameters for positions in the tree to include much more powerful features e.g. marking of leaves and important areas with pins specified in the URL, and making the position of tree view currently stored in the URL be strongly resilient to changes in tree structure and screen of viewer (currently they are not so intelligently done in this regard)

**Comment by hyanwong** [comment]
I'm mainly thinking about other people working on the code. It's very difficult at the moment to work out which files you need to work on if you are interested in modifying the tree viewer only.

We could possibly get around this by collecting the view files concerned with the tree-viewer into a single subdirectory and deliberately pointing the web2py functions there. This is invisible from the outside, but might help us keep sane on the inside.

**Comment by jrosindell** [comment]
I know you have different reasons for suggesting the changes compared to me, though both sets of reasons are valid.  The only thing is that your changes do still require a change to the URL as seen from outside right? Unless we map them across.  I wouldn't suggest making changes to the external URLs any time soon because it could affect the traffic we get to the site or result in broken links that would otherwise have brought users.

**Comment by hyanwong** [comment]
If we put the treeviz view files in a subdirectory, we can point the controller functions at them explicitly, and the URLs don't change at all (invisible from the outside). I see this as a temporary tidying fix.

p.s. (since we are communicating via github issues) - can I save the changes to src/api/search_manager.js that I have pending?

**Comment by jrosindell** [comment]
OK I'd agree to this change if you wanted to do it.

You can save search_manage.js changes but I'm still working on tree layout.html

**Comment by hyanwong** [comment]
This is coded up in https://github.com/OneZoom/OZtree/tree/treepages-in-subdir
