### ISSUE TITLE
Refactor Tours for a single transition promise

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#604]
One annoying thing about the Tour API is the Promise that handles the transition to the tourstop is hidden away in the TourStop, and impossible to spy on and find out when it finishes as a result.

This isn't an insurmountable problem for the tests in #376, but feels ugly. IMO the promise in ``TourStop.play``, and should be moved out to the Tour itself.

* We shouldn't be doing more than one transition at a time, and keeping a reference in a single place (probably shared with the loading promise) can act as a lock to ensure this doesn't happen.
* Tour.js is better placed to manage the state of stops around the current stop.
* Because the promise chain isn't exposed, errors don't have anywhere to go. We can't stop the tour because a flight failed, e.g.

**Comment by hyanwong** [comment]
I can't remember why we did that, but I don't think there was an overriding reason to do so. Is it easy to move it up a level into the tour in general?

It could be that we were trying to make each tour stop relatively independent, so that e.g. we could paste them together in a different order, or even make a new tour by combining tour stops from multiple other tours in a different order. Would this still be possible if the promise was moved into the tour itself?

**Comment by lentinj** [comment]
Relatively easy to do yes, but I'm parking it here for now until there's more evidence it'll be genuinely useful, not just pointless noodling :)

Re-use of tourstops across tours will be invisible at this level, that's for the database to worry about. However, a "You're wrong" tourstop might get re-used in a quiz tour. I don't think this would stop that use-case though.

What we want to preserve though is the TourStop's transition to be relatively arbitrary; the guts of it which choose flight / leap / ..., should stay as part of the TourStop, so it could potentially be customised in future. The Tour should worry about the accounting either side of this.
