### ISSUE TITLE
Documentation on remote control of OneZoom (embedded / JS console)

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#658]
I think it would be very helpful to have documentation of the functions used for tours that can be accessed via the JS console.  I'm thinking specifically of the functions for 

1. playing a whole tour 
2.  highlighting and unhighlighting
3. zooming around
4. tweaking the speed of zoom
5.  looking up OTTID from names
6. Hiding the search and control buttons so that they do not interrupt the screencast

Specific uses for this would be for testing but also to use internally for screencast recording, and maybe to publicise on a page so that more savvy users can record screencasts for whatever uses they may have in mind.

**Comment by lentinj** [comment]
Literally interpreting the request, this is what the controller object documentation should be. ``onezoom.controller`` is the "front door" of the treeviewer, so the generated docs for it should tell you all you need to know. This isn't really true, since they're overly terse or there isn't a proper "front door" for that setting, and you're expected to e.g. monkey around in ``onezoom.controller.config.x``.

But I think what is really needed is more URL documentation, given that's how we do ~all of these things: 

>  playing a whole tour

``set_treestate('?tour=...')``

> highlighting and unhighlighting

``set_treestate('?highlight=...')``

> zooming around

I think it should be ``set_treestate('@aves?init=flight')``, since then you don't have to learn a new thing and you can specify by pinpoints, not OZids as-per the current API (which shouldn't be part of any ~public API).

The main problem with this is we have no way of expressing "from x to y" yet, which would be pretty handy for testing. One could record the flight and use the resulting videos to check for regressions. Maybe ``@aves?init=@mammalia`` would work?

Of course, this makes the ``init`` parameter name look increasingly silly, and ought be renamed if that actually happens.

> tweaking the speed of zoom

This isn't a URL option, but it should be for the embedded use-case.

> looking up OTTID from names

This is an API request, thus part of the API docs if you have lots to look up. If you just have 1--2, then just click on the things or copy the search URL.

> Hiding the search and control buttons so that they do not interrupt the screencast

It should be a URL option if not already, since it's a pretty obvious thing to want for an embedded onezoom.

I don't think it's worth having dedicated narrative documentation for this, beyond "Use ``set_treestate``, read the URL docs" as part of the embedding OneZoom page & developer tools pages.

I'm also wary about publicising the fact that you can do ``onezoom.controller.jiggery_pokery()``, since now that API is set in stone. OTOH, the URL is already set in stone as a public API, so we're not restricting ourselves further here.

**Comment by lentinj** [comment]
Somewhat related, should https://www.onezoom.org/developer.html have the changelog moved to a separate page? It makes the page a lot longer than it need be, and rather misleading (e.g. search for "embed" and you get a link to the v1.2 embed editor).

**Comment by hyanwong** [comment]
We could do, I suppose. I have no strong opinion either way.

**Comment by jrosindell** [comment]
@lentinj @hyanwong 
All this makes sense.  I agree with the developer page issues - I can fix that later.
With regards to publicising - maybe this is a thing to do here is add simple instructions with examples to our management Repo which is private but could be shared with volunteers

**Comment by lentinj** [comment]
I've mulled it a bit more, and think the attempt at mirroring the developer docs in a docs directory isn't the way to go (https://github.com/OneZoom/OZtree/commit/81e799dfeb6146dad4350f95f3e9971f75b8896c & #653). There's already a fair bit of bodging to get links right, which will become unmanageable pretty quickly.

But we still need somewhere to dump this sort of content. I'm leaning towards it being part of onezoom.org rather than it's own site. How about a ``developer`` controller, and views hang off this, e.g. ``views/developer/embedding.html`` @jrosindell ?

**Comment by lentinj** [comment]
The pull request largely solves this I think. The separate developer controller makes it easier to add more stuff to a developer section in the future.

Breaking out the installing OneZoom from docker parts into their own page seems like an obvious next move.

Also, I've still not actually linked to ``/developer/embedding.html`` in the menu, just in case that not linking to it was a conscious choice by @jrosindell. Easy enough to do afterwards though.
