### ISSUE TITLE
Classes to show hide content at tourstop states

### ISSUE THREAD

**Issue by lentinj** [OneZoom/OZtree#732]
Classes to show/hide individual chunks of tourstop content, so you could do something like:

```
@aves : stop_wait=10000 : visible-transition_out
 - content-active_wait "There are lots of birds!"
 - content-active_wait (picture of lots of birds)
 - content-transition_out "But the best bird is..."
@robin : stop_wait=10000 :
 - content-active_wait "The robin!"
 - content-active_wait (video of a robin)
```

**Comment by jrosindell** [comment]
I think this is definitely one for the back burner

**Comment by jrosindell** [comment]
I was just thinking further about this.  I think the most important switch is really content that shows during the transition and content that appears after the transition is completed.  Could this be simplified perhaps into a binary switch on content visibility in the tour card?  If so that might be worth doing depending on the amount of time it will take.

In the tours I've built so far I've just used a whole additional tour stop to deal with the transition with minimal content on the tour card.  I find that this works reasonably well but it raises the issue that the tour stop menu gets filled up with lots of entries that don't feel like real tourstops to the user and might end up having uninspiring titles for the same reason.  Another completely different (possibly not easier) solution would be to allow tourstops to be labelled based on whether they should appear in the tour stop menu as main events or not.  I suspect, however, that this might lead to a lot of plumbing on things like the recording of tour stops seen and the numbering of tourstops.

**Comment by lentinj** [comment]
interstitial tour stops have another problem, they break the back button. Press back, you get to the interstitial tourstop which immediately sends you back to where you came from.

**Comment by jrosindell** [comment]
OK so so we're agreed then that interstitial tour stops are bad and shouldn't happen. 

I was confused by what you said above but I see now that you're letting the tour stop own its transition out content rather than its transition in content.  I thought it would be transition in that's owned by a stop because the first stop needs a transition in whereas the last stop doesn't need a transition out.

I agree this is the way forward now I've understood better - provided that we can still specify general content as we do now as well.  I'm guessing that the title would always be visible no matter what and we'd just have to deal with that and not put spoilers in the title of any tour stop - that's fine.

OK I think this is def. worth implementing if there is time but we'll see how we do as there's a lot on the table now!

**Comment by lentinj** [comment]
Yes sorry, it wasn't the clearest example. I've nearly implemented the below:

```json
        {
            "ott": "@aves",
            "template_data": {
                "visible-transition_in": true,
                "window_text": "There are lots of birds",
                "media": [
                    "lots-of-birds.jpg"
                ]
            }
        },
        {
            "ott": "@robin",
            "template_data": {
                "visible-transition_in": true,
                "window_text": [
                    {"visible-transition_in": true, "text": "But the best bird is..."},
                    {"visible-active_wait": true, "text": "..the robin!"}
                ],
                "media": [
                    {"visible-active_wait": true, "url": "robin-video.webm"}
                ]
            }
        },
```

The differences being:

* You can have many "window_text"'s, like you can with media
* You can add "visible-transition_in" / "visible-active_wait" for individual parts of a tourstop that should only be visible in that state, otherwise they're always visible (which is slightly different to how it works for tourstops, unsatisfyingly).

One possible downside is if going backwards, you won't see "But the best bird is...", because you don't see the flight going backwards. But I don't think it's the end of the world.

**Comment by jrosindell** [comment]
@lentinj this looks great and I don't think the downside you explained above matters at all.

**Comment by lentinj** [comment]
I've converted one of the Frogs interstitial tourstops here: https://github.com/OneZoom/tours/commit/6dd660df7fe83dc6d391606356ec4ae3edda90c0
