### ISSUE TITLE
Wikipedia linkouts for One Tree, One Planet project

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#87]

**Comment by jrosindell** [comment]
1.) switch to remove the maximise button that pings the page out to a separate tab of the browser. (note this switch would also be used for a museum display)

2.) make a simple page with links to EOL, IUCN etc. that can always pop up in cases where there is no wikipedia to show

3.) design decisions - approve the above.

**Comment by jrosindell** [comment]
There are some issues with wikipedia link outs as they stand...

1.) there is a problem (presumably CSS related) where tabs (e.g. Wiki iframe) on mobile (or other small screens e.g. my Safari which I'll attach a screenshot of) go over the side of the page instead of being confined to the bordered area. Yan can also replicate the same bug in Chrome with small screen size only (e.g. by zooming in view at the browser level to make it really small in terms of pixels.

2.) the text size on mobile in the wiki iframe is rather large and certainly not optimal for some reason

3.) opening the birds node wiki page hangs up on my mobile for some reason

**Comment by jrosindell** [comment]
![untitled](https://user-images.githubusercontent.com/3009279/40025090-74f223b6-57c8-11e8-9cfe-e39cae143725.png)

**Comment by hyanwong** [comment]
Here's mine in chrome (with page zoom increased)

![screen shot 2018-05-14 at 22 41 12](https://user-images.githubusercontent.com/4699014/40025169-ac969cfc-57c8-11e8-9852-3eb301981a22.png)

**Comment by jrosindell** [comment]
Also 4.) the scroll bar is wierd in my Chrome - not quite at the edge of the window

**Comment by lentinj** [comment]
The above commit should fix bugs (1) and (4), and should easily cherry-pick to master if you want.

(2) seems to be a feature of Wikipedia's CSS, text size grows as width narrows. No idea why, and I don't think that rewriting CSS is a road we want to start down. If 

I'm not quite sure what (3) means, but birds seems to work fine here. It does have a large tree in the page though, it's possible this was force the content to be so wide you couldn't see anything.

**Comment by lentinj** [comment]
@hyanwong have a look at https://github.com/OneZoom/OZtree/commit/b2f93b34c9c2b358db25dc37894459271ca0c934 above. It adds an extra "ozlinks" tab type (not enabled by default). Add that to your list of tabs and ba-da-bing. However...

The default HTML template is more functional than pretty, but I don't know if this is just debugging or actually used somewhere. Are we breaking anything if we tart up the default for this?

Can we also hide ozspons/ozlinks in the default template, rather than mining through OTOP preferences? They don't count as external links after all, so it seems reasonable, but depends on other uses of this template.

The mapping of id ==> name is stored in UI_layer(), the template could just call this to get at it, but it seems a bit hacky. Should we be moving the tabs data structure elsewhere first, if so where?

**Comment by hyanwong** [comment]
@lentinj great idea. The templates called leaf_linkouts.html and node_linkouts.html in views/tree are simply for ease of debugging (there seemed no reason to keep them private). If you could tart them up a bit that would be great. Normally I put `{{extend ('embed.html' if 'embed' in request.vars else 'layout.html')}}` as the layout at the top, so that the menu bar etc is present on the "non embedded" version but absent when iframed.

I agree about hiding them in the default. I think that will happen automatically (they are not listed on line 30 of treeviewer.py).

I see what you mean about where to store the tabs data structure. Stuff that is used in different controllers I've been putting in `models/_OZglobals.py`, so I suppose you could put it there, or have it as a private function which can be accessed in `modules/OZfunctions.py` and which is `import`ed as necessary. I don't have strong feelings either way, unless one method is much faster than another. The _OZglobals thing is a little more complex because of RAM cache, which I presume doesn't affect functions in OZfunctions.py.

**Comment by hyanwong** [comment]
Have picked that particular css cherry. @lentinj : you might want to update 3.3 from master to get the new UIkit version. Not vital, though.

**Comment by lentinj** [comment]
Yup, I've already grabbed that. Didn't seem to make a difference, which is good :)

**Comment by lentinj** [comment]
I think the only thing left here is "3.) design decisions - approve the above.".

**Comment by hyanwong** [comment]
Excellent (that it didn't have any effect).

**Comment by jrosindell** [comment]
I think this is for Naziha to agree to as she had particular ideas about the linking to other sites - so let's leave the issue open for the inter-sprint testing and evaluation.

**Comment by jrosindell** [comment]
Just looking through this and recalling the conversation with Naziha the main thing remaining is to switch off links in the wikipedia tabs just like they are on life_MD. @hyanwong perhaps you can comment on how this is done as you got it working for life_MD?

**Comment by hyanwong** [comment]
In the .html file in views, the comment says 
```
    #UI_layer->tabs        A name or array of names of tabs to use (names are in OZglobals:tab_definitions and the linkouts() 
    #                       function in tree.py as key names in the url dict) or 'default' for the default set or 'all' for all. 

```

So you should just be able to list which tabs you *do* want there.

**Comment by lentinj** [comment]
Okay, I've rummaged a bit, it's nothing to do with the more obvious ``links`` / ``no_external_links`` options, it's ``embed``.

https://github.com/OneZoom/OZtree/blob/master/views/tree/wikipedia_OZpage.html#L9

Altering to "3", as in life_MD, does the trick.

**Comment by hyanwong** [comment]
Ah, sorry. I misread James' comment. You want *links* turned off, not a particular tab. Yes, `embed=3`. Do change conventions etc if they are confusing.
