### ISSUE TITLE
Settings are reset upon clicking "Popular places" links

### ISSUE THREAD

**Issue by wolfmanstout** [OneZoom/OZtree#870]
If I click on one of the convenient "popular places" links listed when hovering over the search bar, it resets any settings I've changed, such as the visualization shape. This is because it is not passing along the query args.

Simply passing along the query args when generating these links wouldn't truly fix the issue, because this list is populated when the page is first loaded and settings are generally changed after that point. These links either need to invoke javascript that dynamically defines where to navigate to, or else they need to be repopulated any time the query args are changed.

This bug is also present in a lesser form for the links that show up after a search query is entered: if the settings are changed after this point and then one of the links is clicked, it'll reset the settings (for the reason explained above, that the query arg changes are not propagated).

**Comment by lentinj** [comment]
The links are simply ``@species``, without any local state. We make no attempt to add this state---as you say, it'd get stale. What (should) happen is we intercept the link and use ``set_treestate`` to do the changes to the tree instead:

https://github.com/OneZoom/OZtree/blob/889026e68377ae306e8f3ffc60e16223803420cc/views/treeviewer/layout.html#L226-L227

This generally seems to work, and we have no reason to propagate existing query arguments, since ``set_treestate`` only changes the tree state we asked it to. So your settings are preserved.

However, it's not perfect:

* Middle-clicking a search result doesn't preserve settings in the new tab, because the above event handler doesn't get involved
* We only preventDefault once closeAndLeap worked, so any exception on the click event will result in navigating to a new page (without preserving your settings, again because they're not in the URL)

My guess is you're experiencing the latter, a javascript error is being masked by the navigation to a fresh page, which has none of your settings.

**Comment by wolfmanstout** [comment]
Thanks for pointing me in the right direction. I will send a pull request shortly to fix. As it turns out, this is a bug in set_treestate that occurs even if it is called directly via the JS console. It was introduced in https://github.com/OneZoom/OZtree/commit/fe7bd7b8dd3220b24d0cbbf9c71c133d587362bc.
