### ISSUE TITLE
Fiddly to add the current node to common ancestors

### ISSUE THREAD

**Issue by jaredkhan** [OneZoom/OZtree#878]
Sometimes I find I've done a search (and maybe it's taken me a while to find precisely the node I was looking for) and then I decide that I want to do a common ancestors view of this and something else. At the moment, I have to manually search for this node again in the common ancestors view, which feels like an extra step.

**Comment by davidebbo** [comment]
In general, I like the idea of having an easily accessible list of 'recent places'. This would be useful beyond the common ancestor use case.

**Comment by lentinj** [comment]
> add a button to the sufficiently zoomed-in nodes that would add that node to the common ancestor search (rough mockup below) 

Whilst it's something that comes up a lot, I've come out reasonably anti adding-extra-buttons to the leaves. In an ideal world I think the leaf should be one link hotspot, but for that we need the summary page: https://github.com/OneZoom/OZtree/issues/865

But the recent places idea is really good, we should definitely do that. We could have:

* Recently clicked on search results
* Recently clicked on nodes/leaves
* ~Large visible nodes on-screen (covering the use-case of the common-ancestor buttons)

Rather than bombarding the user with lists, it may be nicer to combine them with a do-the-right-thing heuristic, but I'm not sure what that might be off the top of my head.

I don't think these have to be common-ancestor-specific either. Being able to leap back to what you were looking at a few minutes ago sounds pretty useful.

**Comment by lentinj** [comment]
> Maybe 'Popular places' becomes 'Popular and recent places'?

Yeah, this definitely makes sense, the popular places should age out as we find out what you're actually interested in.

But how to combine this list with what's currently visible isn't so obvious. Maybe there isn't a way, and it should stay separate.

**Comment by jaredkhan** [comment]
Thanks for the responses. Agreed that adding buttons to the nodes has obvious downsides. 

One thought on the recent places thing is that it could be similar to whatever is pushing to the browser history at the moment but filtered to just named nodes.

**Comment by lentinj** [comment]
> it could be similar to whatever is pushing to the browser history at the moment

There's a timer that records a new URL, provided the new URL is "different enough". We certainly could redirect these into the history easily enough, but it may well end up recording uninteresting nodes that you're just passing by.

**Comment by jaredkhan** [comment]
The recent places idea is implemented in
https://github.com/OneZoom/OZtree/pull/902
