### ISSUE TITLE
Human leaf to have bespoke images of a person and a fixed number of other images around

### ISSUE THREAD

**Issue by jrosindell** [OneZoom/OZtree#98]
This is following discussion with Naziha and sharing of some mockups of what she would like here.

**Comment by lentinj** [comment]
Made a start on the layout of this, since this isn't dependent on the API. Getting there.

**Comment by lentinj** [comment]
@jrosindell Just had a chat with Naziha about the background, we also looked at the nascent human leaf. One thing that came up is whether the baby Linnaeuses look too similar to being sub-species, which obviously wouldn't be good. Do you have any thoughts?

**Comment by lentinj** [comment]
The above preserves any ``project_*`` portions of the URL in our code, then uses this for an OTOP-specific ``project_user`` querystring option. Are we happy with this before I tell UCAYA that's what it's called?

Obviously ``otop_user`` or something would be more descriptive, however then we'd have to encode knowledge of OTOP in navigation/record.js, which I'd rather not do.

**Comment by jrosindell** [comment]
I agree with this - so if I understand correctly part of the URL will be preserved for third party project specific things and in the case of OTOP they relate to the user and thus to the human leaf image? @hyanwong could you also approve this as after approved it looks like we'll be stuck with it for a while!

**Comment by jrosindell** [comment]
Yes I see what you mean, I also get the feeling that you have a better idea than me of what's best practice here.  Is there a practical reason for passing through everything vs. boxing it in project_* does each choice have advantages or disadvantages?

One thing to bear in mind here so we don't leave ourselves with a problem for the future... the URL is expected to get more complex in future code updates.  For instance - I imagine needing to parse in highlighted areas, dropped pins, highlight styles and information related to tours that are yet to be implemented.  

Another thing - take a URL e.g. http://www.onezoom.org/life.html/@Eukaryota=304358#x795,y-738,w4.0739 The @Eukaryota=304358 part is going to be stable in future versions but might need to be generalised in case the place to be pinpointed doesn't have an open tree ID.  I also don't like #x795,y-738,w4.0739 because it doesn't parse the meaning of what's on screen and just passes literal parameters - hence it doesn't survive well if the URL gets copied from one device and shared to another device with a different screen size - it also doesn't survive well if the tree rearranges itself with a data update and your location isn't so close to OTTid. These problems are solvable but will require a more complex URL parser in future.

So, overall I'll leave it up to you but bear in mind the need for more to be added in future.

**Comment by hyanwong** [comment]
To some extent, "anything goes" as long as the params are in the query string part (`?foo=bar&x=1`) rather than before the question marks or after any hash sign. I'm intending these to be treated just like a normal CGI query string, so we have `vis=x&ol_popup=1234` or whatever. Happy to go with whatever Jamie thinks is suitable within that part of the URL.

I think we want to reserve anything after the hash for what it is normally intended for - i.e. moving to a different location within the same "page", there page in this case means the focus on a particular place on the tree. I also think we need to be very wary about adjusting anything before the "?" part of the URL - there are web2py restrictions about what characters can be used without mucking things up, and the defaults were quite careful chosen, from what I remember (e.g. see https://stackoverflow.com/a/7336244/2667066)

**Comment by lentinj** [comment]
Okay, I've decided to go with ``onezoom.config.custom_querystring_params = ["ucaya_user"]``. This instructs record.js to pass it through, so OTOP code can pick it up. Naturally this shouldn't touch the hash or document path parts of the URL. ``custom_querystring_params`` gives us a trail to follow if we need to work out what parameters are being used, so there are no accidental clashes in future.

**Comment by jrosindell** [comment]
Good solution but opening a new issue with the ideas from above on future enhancements to URL parser
